### PR TITLE
refactor: fix line endings with dos2unix

### PR DESCRIPTION
**Pull request by mfederowicz**
### Summary

fix line endings for selected files: 

```
find -type f -exec dos2unix {} +
```

i think it is better to use LF (linux) line endings because application is developed under linux/mac machines :)

### CODE REVIEW

**Comment by tenshiAMD** [comment]
@mfederowicz hi thanks for contributing however I do not think these are necessary changes

**Comment by tenshiAMD** [comment]
@mfederowicz I think it better to discuss it first since not all are following the same before modifying all files in the codebase.

**Comment by mfederowicz** [comment]
@tenshiAMD afaik there are not all files but thouse which have CRLF format, we should discuss that topic, because most of developers uses linux/mac machines and android studio/vs code :)

**Comment by mfederowicz** [comment]
Good source of knowledge [Article](https://www.aleksandrhovhannisyan.com/blog/crlf-vs-lf-normalizing-line-endings-in-git/)

**Comment by tenshiAMD** [comment]
@mfederowicz hi closing this for now. I will check and resolve this later for us to be sure about the changes. Thanks!

**Pull request closed without merging**
