### PR TITLE
fix: README.md centered badge with a link

### LINKED ISSUE #118: Readme buggies
Screen Shot 2022-08-20 at 4 12 35 PM
Screen Shot 2022-08-20 at 4 13 13 PM

Seems like the shields.io badges don't like to be centered in the Markdown syntax, HTML <img tag is needed instead
Also, the bot defaults seem to have messed up the link again.
I'll make a PR with fixes in a minute

### PR DESCRIPTION
**Pull request by PickleNik**
fixes #118

### CODE REVIEW

**Comment by ramsy0dev** [comment]
@KalleHallden said to not modifie or remove the section of contributors so i think this will not get merged

**Comment by PickleNik** [comment]
> @KalleHallden said to not modifie or remove the section of contributors so i think this will not get merged

this does not modify or remove the section of cotributors

**Comment by PickleNik** [comment]
Before:
image
After:
Screen Shot 2022-08-20 at 4 29 48 PM

**Comment by PickleNik** [comment]
sorry, didn't look, #107 already fixed that, only thing needed is #120 
(edit: #107 had some issues)

**Comment by PickleNik** [comment]
Reopening this in case that #107 isn't fixed (close if #107 changes to a centered badge with correct link)

**Pull request merged**
