### PR TITLE
Centering the app logo and the All Contributors badge in the README.md

### PR DESCRIPTION
**Pull request by ramsy0dev**
Centering the badge and the app logo
to center the badge i find out that it is better to call the badge as an image then we can add the a tag to redirect to the [contributors](https://github.com/KalleHallden/exer_log/graphs/contributors)  page.
as for the logo we set the align="center"

### CODE REVIEW

**Comment by PickleNik** [comment]
I assume @KalleHallden had set up the current all-contributors shield/badge with https://allcontributors.org/, which is meant to be used with #Contributors section in the readme, similar to the one over at https://github.com/all-contributors/all-contributors#contributors- (which is why it deadlinked to #contributors- prior to this commit)

That's why the badge says 4 and not 12, otherwise it would make more sense to use the GitHub contributors badge with the link to gh contributors page like in this commit.

No real preference here, just trying to clear up the badge confusion :)

**Comment by PickleNik** [comment]
Whoops, just scrolled down 😅, apparently there's a contributors section in this readme as well https://github.com/KalleHallden/exer_log#contributors

I am guessing it deadlinks because of the dash(-) at the end,
https://github.com/all-contributors/all-contributors#contributors- have an emoji, hence the dash in the end.

Created #95 to fix that

**Review by PickleNik — CHANGES_REQUESTED** [review]
Keep the align="center", it's cool 👍, but maybe undo the badge stuff,
explainer as to why in https://github.com/KalleHallden/exer_log/pull/88#issuecomment-1220232823

**Comment by ramsy0dev** [comment]
Ok i didn't know i should change the badge because @dinurymomshad told me to center them so i say ok

**Comment by ramsy0dev** [comment]
ok i changed the badge from 
 
to

**Pull request closed without merging**
