### PR TITLE
Fixing the color issue in ```onNetworkConnectionError.dart```

### PR DESCRIPTION
**Pull request by ramsy0dev**
Fixing the color that simply a mistake i made by not setting values to `redBackgroundColor` and `textColorBlue` 

and also using ```connectivity_plus``` instead of ```connectivity``` because this package does support sound null safety

<h3>why did this happend ?</h3>
 i looked into the pull requests that got merged @jorre127 when he did this [PR](https://github.com/KalleHallden/exer_log/pull/94) he accidently removed the colors from the global.dart file and his PR was merged after my PR was merged, and that cause to  `redBackgroundColor` and `textColorBlue` not being found

so it will be nice to have somone look through PR's and make sure they don't delet or remove a piece of code that well be used in an other PR

### CODE REVIEW

**Comment by jorre127** [comment]
@0RaMsY0  This issue is already fixed in PR #106. This wasn't an accident, we're not using the colors in the global.dart file anymore that's why they were removed. Colors are now stored in the AppTheme class. But yeah the issue was indeed caused by both our PR's being merged back to back, already made a discussion about this and I think @tenshiAMD is working on this issue with mergeable. I think that might allow us to force a PR too be reviewed before it can be merged, so this doesn't happen again. So could you close this PR so there's no confusion? Or maybe make a separate one that only updates the connectivity_plus.

**Comment by mfederowicz** [comment]
Hi @0RaMsY0 i know that fixing the bug is important, but why did you commit changes in pubspcec.* files, they are not connected with the problem, maybe we should wait for merging changes from https://github.com/KalleHallden/exer_log/pull/106, of course that is only sugestion :P

**Comment by ramsy0dev** [comment]
i changed the package that i use to view network from ```connectivity``` to  [connectivity_plus](https://pub.dev/packages/connectivity_plus#connectivity_plus) and i instaled locally so the dart extention in vs code automaticlly do changes to the pubspec they well not effect any thing
the reason why i changed the package is that [connectivity_plus](https://pub.dev/packages/connectivity_plus#connectivity_plus) support sound null safety

**Comment by ramsy0dev** [comment]
@jorre127 whene i first start creating the feature i looked to the files and found them using the global.dart as colors and by then your PR wasn't merged yet so i had no idea there was a theme_color.dart
i'm very sorry if this causes any trouble to you guys

**Comment by ramsy0dev** [comment]
OK i will close this now as you said

**Pull request closed without merging**
