### PR TITLE
CONTRIBUTING.md rename & README.md file spelling fixes

### PR DESCRIPTION
**Pull request by md-siam**
1. GitHub can not detect the `CONTRIBUTING.md` file, therefore I change it to `CODE_OF_CONDUCT.md`

Screen Shot 2022-08-17 at 6 37 53 AM

2. Spelling fix in `README.md`

### CODE REVIEW

**Comment by dinurymomshad** [comment]
@md-siam thanks for your work. But the **Code of conduct** is lil bit different from _contributing.md_. In my opinion, we should have a separate file for the **Code of conduct**. We should not rename _contributing.md_ as the **Code of conduct**.

Links:
[Community guideline for health file](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file)
[Example code of conduct](https://github.com/18F/code-of-conduct/blob/master/code-of-conduct.md)
[Example of contributing.md](https://github.com/18F/code-of-conduct/blob/master/CONTRIBUTING.md)

**Comment by md-siam** [comment]
O I see. 
But 80% information written in the `contributing.md` file is similar to the `CODE_OF_CONDUCT.md`.

**Comment by dinurymomshad** [comment]
I see what you mean. Our `contributing.md` needs to be updated. Content related to `Code of conduct` needs to move to a separate file.

**Comment by dinurymomshad** [comment]
The issue title should be
### Update contributing health file.
This should only focus on updating the contents of `contributing.md`. Which means removing the `Code of conduct` related contents. Improving the already existing guidelines regarding contributing.

Then on a separate PR, titled 
### Code of conduct health file
you can add the contents related to code of conduct.

In each case, it is expected that references in `readme.md` will change. So no need to mention that in the title.

**Comment by dinurymomshad** [comment]
@KalleHallden there was some review though. :(

**Comment by md-siam** [comment]
[KalleHallden](https://github.com/KalleHallden) do not rush into **merging** a random pull request in an open-source project. It is **ok** for markup document, therefore .md, files. 
But do not merge code-based pull requests without reviewing them at least once.

**Pull request merged**
