### PR TITLE
refactor: Introduced freezed, fpdart and hooks to refactor LandingPage flow

### PR DESCRIPTION
**Pull request by linxydmhg**
### Summary

Added freezed, hooks, fpdart dependencies and refactored the LandingPage to make use of them. Freezed will allow for easy state object generation and creation, hooks eliminates much boilerplate code and makes Stateful widgets Stateless, and fpdart allows for functional types for better null/error handing. This PR just refactors the LandingScreen to use all those packages. 
This is mostly future-proofing, as the app and complexity grows, these packages become more indispensable.

### Other Information

AuthenticationController was split up into 2 classes due to increasing complexity.
AuthenticationRepository was also changed to use TaskEither type from fpdart, eliminating the need for try/catch blocks in the controller classes.
Due to freezed/json_annotation package, now you have to call this command before running the project to generate the additional classes
`flutter pub run build_runner build`
or possibly
`flutter pub run build_runner build --delete-conflicting-outputs`

We should also update the Model objects to use freezed, but this should be a separate issue.

### CODE REVIEW

**Comment by momshaddinury** [comment]
@linxydmhg thank you for such effort. My concern is that many people aren't familiar with **freezed**, **fpdart**, and **hooks**. Don't want people to stop contributing because they don't know **Riverpod**, **Freezed**, **fpdart** (_though I vote to introduce fpdart_), and **Hooks**.

There was a discussion to introduce a **base view** but that was also stopped considering it would make things difficult for other contributors.

@jorre127 what do you think?

**Comment by jorre127** [comment]
@dinurymomshad hmm yeah this is a hard one. If we would add all these I don't think the average person is going to be able contribute because we are so far distanced from "normal" flutter. Don't think most people even work with packages that change the state management like riverpods, and if you add functional programming on top of that most people are going to be lost and will probably only be able to contribute with small standalone widgets that don't handle logic. But on the other hand I do think this makes the code better and more stable. So it's probably something @KalleHallden  has to decide on.

Do we want better stable code that only a few people will be able to work on (more burden will fall on these people then to add new features to the project) or do we want to keep it more simple and allow more people to be able to contribute?

**Comment by momshaddinury** [comment]
> @dinurymomshad hmm yeah this is a hard one. If we would add all these I don't think the average person is going to be able contribute because we are so far distanced from "normal" flutter. Don't think most people even work with packages that change the state management like riverpods, and if you add functional programming on top of that most people are going to be lost and will probably only be able to contribute with small standalone widgets that don't handle logic. But on the other hand I do think this makes the code better and more stable. So it's probably something @KalleHallden has to decide on.
> 
> Do we want better stable code that only a few people will be able to work on (more burden will fall on these people then to add new features to the project) or do we want to keep it more simple and allow more people to be able to contribute?

I'd vote on keeping it simple until we are done organizing everything. We have tons of things left to do. Only the landing page is somewhat organized.

**Comment by KalleHallden** [comment]
I honestly don't know which way to go. I haven't worked with these sort of things, my applications have usually been dead simple. So I am very lost when it comes to pretty much all of this stuff, I do think what you are suggesting is a good idea long term. Structure usually is. But short term we may need to keep it simple. But I feel very unqualified to even suggest something here.

**Comment by momshaddinury** [comment]
Closing the pull request.

**Pull request closed without merging**
