### PR TITLE
raised button text on login page now changes

### PR DESCRIPTION
**Pull request by HaardikBhagtani**
1- a) RaisedGradientButton text "Sign up" and  "Login" will now change on the tab's switch.
    b) controller will be disposed of when it is used and the page is changed, so the listener unnecessarily doesn't use the resources

2- in app/build.gradle, changed the GradleException to FileNotFoundException ([reference](https://github.com/flutter/flutter/issues/29608#issuecomment-548649907))

### CODE REVIEW

**Comment by Scount** [comment]
@HaardikBhagtani The issue with tab switch was fixed in #16. Can you update this pull request so that only the second case is addressed?

**Comment by HaardikBhagtani** [comment]
@Scount, could you help me how to update someone else's pull request? I am not new to git but a bit amateur in the forking and changing branches of git

**Comment by Scount** [comment]
@HaardikBhagtani You can try [this](https://tighten.com/blog/adding-commits-to-a-pull-request/). But i have to say i am using [Github Desktop](https://desktop.github.com/). To get the pull request locally i click on the Code button in the top right corner on the pull request and use the checkout with Github Desktop.

pull_request
Now proceed like any other branch.

**Comment by HaardikBhagtani** [comment]
okay I will create a new commit for points 1a and 2 and the branch to be changed to Login then.

**Pull request closed without merging**
