### PR TITLE
feat: implement CI for testing builds

### LINKED ISSUE #163: Run build checks in every PR
We need this so we can be sure every PR does not break the build.

### PR DESCRIPTION
**Pull request by tenshiAMD**
### Summary

This is to implement CI for testing builds for we can ensure all builds are working properly before merging PR.

### Other Information

This will resolve https://github.com/EXERLOG/exer_log/issues/163.

### CODE REVIEW

**Comment by jorre127** [comment]
Oh damn this is nice, didn't know GitHub had this feature. Is it completely free to run the builds? Because the build times on iOS are really long because of the firestore package, so that might be a problem if you have to pay after a while, but if it's completely free then it's no problem.

**Comment by tenshiAMD** [comment]
@jorre127 yeah we might disable iOS for now since it takes a lot of time to finish (I think will never stop - this might be a bug but I will try to reach out for support).

**Comment by jorre127** [comment]
@tenshiAMD Yeah don't know if it's a bug or just that iOS builds are long. Because I also had this in a recent project and for some reason adding the Firestore package increased the build time to 1+ hours.

**Comment by tenshiAMD** [comment]
> @tenshiAMD Yeah don't know if it's a bug or just that iOS builds are long. Because I also had this in a recent project and for some reason adding the Firestore package increased the build time to 1+ hours.

@jorre127 looks like you are correct about that ... I did not know that took so much time that I thought it will be forever.

https://github.com/tenshiAMD/exer_log/runs/8159710423?check_suite_focus=true

**Comment by tenshiAMD** [comment]
@jorre127 can you approve this? then we can merge this later after all build passes. Thanks!

**Comment by jorre127** [comment]
@tenshiAMD Yeah its a really annoying issue and I don't think there is a fix for it as long as were using firebase.

**Comment by jorre127** [comment]
@tenshiAMD Is it normal that the workflows seem to be created in groups of two ? 
Screenshot 2022-09-02 at 18 50 30

**Comment by jorre127** [comment]
> @tenshiAMD Is it normal that the workflows seem to be created in groups of two ?
> Screenshot 2022-09-02 at 18 50 30

Because now it seems a little overkill to have so many builds running for 1 PR. Maybe you can add it that if a build is already running and the PR gets updated the build gets cancelled and it starts the new build. Or is this not possible?

**Comment by tenshiAMD** [comment]
> @tenshiAMD Is it normal that the workflows seem to be created in groups of two ?

@jorre127 nevermind that since I forced push this branch, our only concern is the checks linked in this PR.

**Review by jorre127 — APPROVED** [review]

**Comment by tenshiAMD** [comment]
@all-contributors please add doc, data and test

**Comment by tenshiAMD** [comment]
@all-contributors please add doc and data and test

**Comment by tenshiAMD** [comment]
@all-contributors please add @tenshiAMD doc and data and test

**Pull request merged**
