### PR TITLE
removed warning of @immutable marked class

### PR DESCRIPTION
**Pull request by himanshu634**

### CODE REVIEW

**Comment by KalleHallden** [comment]
This looks good, would you mind looking into the merge conflicts?

**Comment by himanshu634** [comment]
I don't have write access. Can you give me that access so that I can see merge conflicts?

**Comment by momshaddinury** [comment]
@himanshu634 create a temporary branch synced with upstream/master. Then try merging that with your current branch on your repository. That should let your solve conflicts on your end. Then push again.
CC: @KalleHallden

**Comment by edicoderr** [comment]
Screenshot from 2022-08-20 08-48-18
I think here is a bug or not?
Idk?

**Comment by momshaddinury** [comment]
> Screenshot from 2022-08-20 08-48-18 I think here is a bug or not? Idk?

What flutter version are you using?

**Comment by himanshu634** [comment]
I gotta check it soon..

**Comment by himanshu634** [comment]
I gonna check it soon..

**Comment by ramsy0dev** [comment]
> Screenshot from 2022-08-20 08-48-18 I think here is a bug or not? Idk?

why are you running the app on chrome i doesn't support it yet try running it on Android or IOS

**Comment by jorre127** [comment]
@himanshu634 are you still working on this or should this be closed ?

**Comment by himanshu634** [comment]
I am working will update soon, busy with my schedule...

**Review by tenshiAMD — CHANGES_REQUESTED** [review]
@himanshu634  Hi, please rebase to alpha branch then fix conflicts. Thanks!

Are the changes in `pubspec.lock` really necessary?

**Comment by himanshu634** [comment]
I think flutter version can be a problem

**Comment by himanshu634** [comment]
I am closing this request.

**Pull request closed without merging**
