### PR TITLE
Repo cleanup

### PR DESCRIPTION
**Pull request by HacDan**
Moved code to the root of the repo and removed the .DS_Store file. Checked .gitignore into VC.

### CODE REVIEW

**Comment by dinurymomshad** [comment]
This should wait until #55 is merged. Or you can work on top of my branch? That'd be great.

**Comment by MarkusZoppelt** [comment]
This should be merged. The earlier the better since future PRs can use the folder structure.

**Comment by dinurymomshad** [comment]
@MarkusZoppelt @HacDan this was taken care of in the above mentioned PR. Please check to confirm.

**Comment by KalleHallden** [comment]
Was all of this solved in #55?

**Comment by dinurymomshad** [comment]
@KalleHallden yes. Looks like that. You can verify by going to the master branch. We don't have ".DS_Store". ".gitIgnore" is added. The app is moved to the root

**Pull request closed without merging**
