### PR TITLE
Fixed the contributing badge in README.md

### PR DESCRIPTION
**Pull request by cj-praveen**
KalleHallden_exer_log - Brave 8_17_2022 7_54_43 PM

<br>

KalleHallden_exer_log - Brave 8_17_2022 7_57_35 PM

### CODE REVIEW

**Comment by momshaddinury** [comment]
Duplicate of #81 
### WARNING: WRONG ISSUE LINKED!!! THIS IS NOT RELATED TO #64 

CC: @KalleHallden

**Comment by cj-praveen** [comment]
I'm sorry, but I haven't seen that my PR is linked with the wrong issue. I just started learning PR recently. 
I just wanted to say that instead of the badge, the line of code was displayed, but now it's fixed 😀.

@KalleHallden @dinurymomshad

**Comment by momshaddinury** [comment]
> I'm sorry, but I haven't seen that my PR is linked with the wrong issue. I just started learning PR recently. 
> 
> I just wanted to say that instead of the badge, the line of code was displayed, but now it's fixed 😀.
> 
> 
> 
> @KalleHallden @dinurymomshad 

It's alright. Try to work on something else

**Comment by cj-praveen** [comment]
Yeah

**Pull request closed without merging**
