### PR TITLE
fixed problem with colours not found

### LINKED ISSUE #104: I keep getting an error when i try to compile it looks like a syntax error
image

### LINKED ISSUE #116: noNetworkConnectionSnackBar.dart Error
`noNetworkConnectionSnackBar.dart` currently contains the following code:

```dart
import 'package:exerlog/UI/global.dart';
import 'package:flutter/material.dart';

SnackBar noNetworkConnectionSnackBar() => SnackBar(
      backgroundColor: redBackgroundColor,
      duration: Duration(
          days:
              365), // set to a year so that it doesn't disappear automatically untill the user clicks on the Dismiss button
      content: Text('No network connection, please check your connection'),
      action: SnackBarAction(
        textColor: textColorBlue,
        label: 'Dismiss',
        onPressed: () {},
      ),
    );
```

`redBackgroundColor` and `textColorBlue` do not exist in `global.dart`

### PR DESCRIPTION
**Pull request by jorre127**
closes #104 closes #116 Fixed a problem were there were references to colours in the global.dart file that didn't exist anymore.

### CODE REVIEW

**Review by momshaddinury — CHANGES_REQUESTED** [review]
Please change the following

1. SnackBars directory to snack_bars
2. noNetworkConnectionSnackBar.dart to no_network_connection_snackbar.dart

**Comment by jorre127** [comment]
@dinurymomshad Fixed the file names

**Comment by momshaddinury** [comment]
@jorre127 @KalleHallden I don't think we should merge this. Because #99 this needs more discussion. Since #93 was closed by @KalleHallden, I am cherry-picking commits to reopen the PR. While doing that noticed #99 introduces bugs and the implementation requires more in-depth discussion. Few issues:

1. Since we are using riverpod, this implementation should also be implemented via riverpod
2. It introduces a bug
3. Solution only handles calendar screen but it should be applicable for all screens.
4. While checking @jorre127 theme implementation I realized we need a BaseView class to implement the DRY (Don't repeat yourself) concept.

### And, as @jorre127 expressed concern in the discussion, we should not quickly merge things. It's creating more chaos.

**Comment by jorre127** [comment]
@dinurymomshad I agree with the fact that we need to rework the implementation of the no internet snackbar, but I think we should merge this pr, because it's just a fix, and I think it's important to merge it seeing as the project doesn't compile right now.

**Comment by jorre127** [comment]
@dinurymomshad As for DRY you got any suggestions for this? I was thinking of creating a widget like baseScreen for example that contains al the boiler plate code for a new screen (AppBar, ThemeProvider, etc.), but then you would still have to use this widget on every screen. Don't know if there's a clean way where you don't have to repeat anything, but maybe you got a suggestion?

**Comment by momshaddinury** [comment]
> @dinurymomshad I agree with the fact that we need to rework the implementation of the no internet snackbar, but I think we should merge this pr, because it's just a fix, and I think it's important to merge it seeing as the project doesn't compile right now.

#112 should be merged first then. Otherwise, I will have to resolve the conflict again.

**Comment by momshaddinury** [comment]
> @dinurymomshad As for DRY you got any suggestions for this? I was thinking of creating a widget like baseScreen for example that contains al the boiler plate code for a new screen (AppBar, ThemeProvider, etc.), but then you would still have to use this widget on every screen. Don't know if there's a clean way where you don't have to repeat anything, but maybe you got a suggestion?

I think we should continue this in the discussion section. Opening a new thread.

**Comment by momshaddinury** [comment]
> > @dinurymomshad As for DRY you got any suggestions for this? I was thinking of creating a widget like baseScreen for example that contains al the boiler plate code for a new screen (AppBar, ThemeProvider, etc.), but then you would still have to use this widget on every screen. Don't know if there's a clean way where you don't have to repeat anything, but maybe you got a suggestion?
> 
> I think we should continue this in the discussion section. Opening a new thread.

@jorre127 https://github.com/KalleHallden/exer_log/discussions/114

**Pull request merged**
